version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
    - "8088:80"
    volumes:
    - ./backend:/var/www/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
    - "4306:3306"
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: portfolio
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
    - ./backend:/var/www/html
    ports:
    - "9000:9000"
    networks:
      - laravel
  queue:
    build:
      context: supervisor
      dockerfile: Dockerfile
    container_name: queue
    volumes_from:
      - php
    networks:
      - laravel
  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm start
    container_name: frontend
    restart: unless-stopped
    volumes:
    - "./app/node_modules"
    - "./frontend/:/app"
    depends_on:
      - nginx
      - php
    ports:
      - "4200:4200"
    networks:
      - laravel
  
  